name: Luacheck

on:
  push:
    paths:
      - '**.lua'
  pull_request:
    paths:
      - '**.lua'

jobs:

  lint:
    runs-on: ubuntu-latest
    env:
      LUA_VERSION: 5.1.5
      LUAROCKS_VERSION: 2.4.2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Lua environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev libncurses-dev
        wget https://www.lua.org/ftp/lua-${{ env.LUA_VERSION }}.tar.gz -O - | tar -xzf -
        cd lua-${{ env.LUA_VERSION }}
        make linux
        sudo make install

    - name: Install LuaRocks and Luacheck
      run: |
        wget https://luarocks.org/releases/luarocks-${{ env.LUAROCKS_VERSION }}.tar.gz -O - | tar -xzf -
        cd luarocks-${{ env.LUAROCKS_VERSION }}
        ./configure --with-lua-bin=/usr/local/bin --prefix=$HOME/.luarocks
        make build
        sudo make install
        export PATH=$HOME/.luarocks/bin:$PATH
        luarocks install luacheck

    - name: Run Luacheck
      run: luacheck . --no-color --codes --formatter=default --max-line-length=false --ignore='111,113,212'
