name: Pack and Release

on:
  workflow_dispatch:
    inputs:
      test_branch:
        description: 'Simulate branch name (main or other)'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - dev-testing

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  
jobs:
  pack-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Environment Variables
        id: vars
        run: |
          REPO_NAME=$(echo "${{ github.event.repository.name }}")
          if [ "${{ inputs.test_branch }}" = "main" ]; then
            SUFFIX="ElvUI_6.09"
          else
            SUFFIX="ElvUI_7"
          fi
          
          echo "ZIP_NAME=${REPO_NAME}_${SUFFIX}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Prepare and Package Files
        run: |
          mkdir -p "${{ env.REPO_NAME }}"
          rsync -av --exclude '.*' --exclude "${{ env.REPO_NAME }}" ./ "${{ env.REPO_NAME }}/"
          cd "${{ env.REPO_NAME }}"
          zip -r "../${{ env.ZIP_NAME }}.zip" .

      - name: Upload Test Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: "${{ env.ZIP_NAME }}.zip"